//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revo.SatSolver.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Revo.SatSolver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid character at line {0}, column {1}: &apos;{2}&apos;. ähnelt.
        /// </summary>
        internal static string CnfParserException_InvalidCharacter {
            get {
                return ResourceManager.GetString("CnfParserException_InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid line (e.g. leading whitespace) at line {0}. ähnelt.
        /// </summary>
        internal static string CnfParserException_InvalidLine {
            get {
                return ResourceManager.GetString("CnfParserException_InvalidLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid problem format &apos;{0}&apos; at line {1}. Expected format &apos;cnf&apos;. ähnelt.
        /// </summary>
        internal static string CnfParserException_InvalidProblemFormat {
            get {
                return ResourceManager.GetString("CnfParserException_InvalidProblemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing or invalid problem definition at line {0}. ähnelt.
        /// </summary>
        internal static string CnfParserException_InvalidProblemLine {
            get {
                return ResourceManager.GetString("CnfParserException_InvalidProblemLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Literal &apos;{0}&apos; out of range (1 - {1}) at line {2}, column {3}. ähnelt.
        /// </summary>
        internal static string CnfParserException_LiteralOutOfRange {
            get {
                return ResourceManager.GetString("CnfParserException_LiteralOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing {0} clause(s) at line {1}. ähnelt.
        /// </summary>
        internal static string CnfParserException_MissingClauses {
            get {
                return ResourceManager.GetString("CnfParserException_MissingClauses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing literal in line {0}, column {1}. ähnelt.
        /// </summary>
        internal static string CnfParserException_MissingLiteral {
            get {
                return ResourceManager.GetString("CnfParserException_MissingLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing clause termination character &apos;0&apos; at line {0}, column {1}. ähnelt.
        /// </summary>
        internal static string CnfParserException_MissingTerminator {
            get {
                return ResourceManager.GetString("CnfParserException_MissingTerminator", resourceCulture);
            }
        }
    }
}
